let dataMoc = [
  {
    id: 1,
    name: "Leoline",
    surname: "Elkin",
    email: "lelkin0@opera.com",
    gender: "Female",
    password: "nCbulcb5nB2V",
  },
  {
    id: 2,
    name: "Haydon",
    surname: "Andresen",
    email: "handresen1@cam.ac.uk",
    gender: "Male",
    password: "wJ0M0PrpHhY",
  },
  {
    id: 3,
    name: "Janene",
    surname: "Happer",
    email: "jhapper2@hugedomains.com",
    gender: "Female",
    password: "aRP0KD",
  },
  {
    id: 4,
    name: "Pegeen",
    surname: "Mintram",
    email: "pmintram3@last.fm",
    gender: "Female",
    password: "LSbjKB",
  },
  {
    id: 5,
    name: "Jacinda",
    surname: "Enrico",
    email: "jenrico4@nyu.edu",
    gender: "Female",
    password: "j9Ukw3u",
  },
  {
    id: 6,
    name: "Tessy",
    surname: "Bazeley",
    email: "tbazeley5@buzzfeed.com",
    gender: "Female",
    password: "dZ13jghaz7",
  },
  {
    id: 7,
    name: "Erny",
    surname: "Petrulis",
    email: "epetrulis6@angelfire.com",
    gender: "Non-binary",
    password: "1AXmR6RxtwB",
  },
  {
    id: 8,
    name: "Catharina",
    surname: "Mattock",
    email: "cmattock7@printfriendly.com",
    gender: "Bigender",
    password: "wXMYGEJN",
  },
  {
    id: 9,
    name: "Dannel",
    surname: "McAloren",
    email: "dmcaloren8@chronoengine.com",
    gender: "Male",
    password: "YjfE2QGrgw",
  },
  {
    id: 10,
    name: "Vicki",
    surname: "Klaes",
    email: "vklaes9@oakley.com",
    gender: "Female",
    password: "oxN8yzIF8",
  },
  {
    id: 11,
    name: "Selina",
    surname: "McGeachy",
    email: "smcgeachya@statcounter.com",
    gender: "Female",
    password: "L4yxiN5GLq",
  },
  {
    id: 12,
    name: "Zora",
    surname: "Billham",
    email: "zbillhamb@cnbc.com",
    gender: "Female",
    password: "Ws5j3Oxa7C",
  },
  {
    id: 13,
    name: "Margarete",
    surname: "Guwer",
    email: "mguwerc@rakuten.co.jp",
    gender: "Female",
    password: "8vXGkmff1c",
  },
  {
    id: 14,
    name: "Stinky",
    surname: "Pandya",
    email: "spandyad@huffingtonpost.com",
    gender: "Polygender",
    password: "fLS5O3pR90",
  },
  {
    id: 15,
    name: "Guilbert",
    surname: "Cleever",
    email: "gcleevere@columbia.edu",
    gender: "Male",
    password: "Si4ple",
  },
  {
    id: 16,
    name: "Nikola",
    surname: "Le Pruvost",
    email: "nlepruvostf@themeforest.net",
    gender: "Male",
    password: "aZC3Q4wE",
  },
  {
    id: 17,
    name: "Ingeberg",
    surname: "Fraczkiewicz",
    email: "ifraczkiewiczg@howstuffworks.com",
    gender: "Female",
    password: "S2DOI6Muswy",
  },
  {
    id: 18,
    name: "Camella",
    surname: "MacCarroll",
    email: "cmaccarrollh@uol.com.br",
    gender: "Female",
    password: "xOo15g9N9Qz",
  },
  {
    id: 19,
    name: "Charlena",
    surname: "Adderley",
    email: "cadderleyi@house.gov",
    gender: "Female",
    password: "alcIlyQJMr",
  },
  {
    id: 20,
    name: "Kitty",
    surname: "Wartnaby",
    email: "kwartnabyj@blog.com",
    gender: "Female",
    password: "RheXnQ",
  },
];

export { dataMoc };
